services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - DB_URL=${DB_URL_CONTAINER}
    depends_on:
      - db
    volumes:
      - ./api:/app/api/

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432" # To avoid conflict if you have a postgres process active
    env_file:
      - ./.env
    volumes:
      - /var/cache/postgres_data_2:/var/lib/postgresql/data
      - db-volume:/var/lib/postgresql/data

volumes:
  db-volume: